apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-axum-app
  labels:
    app: rust-axum-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rust-axum-app
  template:
    metadata:
      labels:
        app: rust-axum-app
    spec:
      containers:
        - name: rust-axum-app
          image: kssandhu01/rust-axum-askama-htmx:latest
          ports:
            - containerPort: 8082
          resources:
            limits:
              cpu: "0.5"
              memory: "256Mi"
            requests:
              cpu: "0.25"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 10
      nodeSelector: {} # Optional: Add constraints for node selection
---
apiVersion: v1
kind: Service
metadata:
  name: rust-axum-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8082
      protocol: TCP
  selector:
    app: rust-axum-app
