name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install npm dependencies
        run: |
          cd tailwind
          npm install

      - name: Set up environment variables
        run: echo "DATABASE_URL=sqlite://sqlite.db" >> $GITHUB_ENV

      - name: Create SQLite Database
        run: |
          touch sqlite.db
          chmod 666 sqlite.db

      - name: Run database migrations
        run: |
          cargo install sqlx-cli -F sqlite
          sqlx database create
          sqlx migrate run

      - name: Build CSS with Tailwind
        run: |
          cd tailwind
          npm run build-css-prod

      - name: Build Rust Application
        run: cargo build --release

      - name: Run Tests
        run: cargo test --verbose
